#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mirapp.Resource", IsApplication=true)]

namespace Mirapp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int Languages = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int book32 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int book48 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int delete2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int delete3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int edit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int list_icon_bg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int list_item_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int listitem = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int trash = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060017
			public const int DictionaryAddButton = 2131099671;
			
			// aapt resource value: 0x7f060018
			public const int DictionaryDeleteButton = 2131099672;
			
			// aapt resource value: 0x7f060026
			public const int DictionaryEasyGameStartButton = 2131099686;
			
			// aapt resource value: 0x7f060024
			public const int DictionaryGameEndButton = 2131099684;
			
			// aapt resource value: 0x7f06001a
			public const int DictionaryGameError = 2131099674;
			
			// aapt resource value: 0x7f06001b
			public const int DictionaryGameFROMButton = 2131099675;
			
			// aapt resource value: 0x7f060007
			public const int DictionaryGameOverResult = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int DictionaryGameOverResultGameLevel = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int DictionaryGameOverResultLanguage = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int DictionaryGameOverResultSuccessCount = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int DictionaryGameOverResultSuccessPercentage = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int DictionaryGameOverResultSuccessTime = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int DictionaryGameOverResultTryCount = 2131099650;
			
			// aapt resource value: 0x7f060023
			public const int DictionaryGameResult = 2131099683;
			
			// aapt resource value: 0x7f060025
			public const int DictionaryGameSpinner = 2131099685;
			
			// aapt resource value: 0x7f060006
			public const int DictionaryGameStartAgainButton = 2131099654;
			
			// aapt resource value: 0x7f060022
			public const int DictionaryGameTime = 2131099682;
			
			// aapt resource value: 0x7f06001c
			public const int DictionaryGameToButton1 = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int DictionaryGameToButton2 = 2131099677;
			
			// aapt resource value: 0x7f06001e
			public const int DictionaryGameToButton3 = 2131099678;
			
			// aapt resource value: 0x7f06001f
			public const int DictionaryGameToButton4 = 2131099679;
			
			// aapt resource value: 0x7f060020
			public const int DictionaryGameToButton5 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int DictionaryGameToButton6 = 2131099681;
			
			// aapt resource value: 0x7f060028
			public const int DictionaryHardGameStartButton = 2131099688;
			
			// aapt resource value: 0x7f06000f
			public const int DictionaryListRowDelete = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int DictionaryListRowEdit = 2131099665;
			
			// aapt resource value: 0x7f060008
			public const int DictionaryMainButton = 2131099656;
			
			// aapt resource value: 0x7f060027
			public const int DictionaryMiddleGameStartButton = 2131099687;
			
			// aapt resource value: 0x7f06000d
			public const int DictonaryRowToWord = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int DictonaryRowWord = 2131099660;
			
			// aapt resource value: 0x7f06000b
			public const int DictonaryRowWordID = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int FROMText = 2131099666;
			
			// aapt resource value: 0x7f06000a
			public const int LinearLayoutDictionaryListRow = 2131099658;
			
			// aapt resource value: 0x7f06000e
			public const int LinearLayoutDictionaryListRowButtonDelete = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int LinearLayoutDictionaryListRowButtonEdit = 2131099664;
			
			// aapt resource value: 0x7f060029
			public const int Listview1 = 2131099689;
			
			// aapt resource value: 0x7f060015
			public const int TOText = 2131099669;
			
			// aapt resource value: 0x7f060019
			public const int TranslateButton = 2131099673;
			
			// aapt resource value: 0x7f060016
			public const int TranslatedWordText = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int WordTextAutoComplete = 2131099668;
			
			// aapt resource value: 0x7f06002a
			public const int fragmentContainer = 2131099690;
			
			// aapt resource value: 0x7f060009
			public const int list_icon = 2131099657;
			
			// aapt resource value: 0x7f06002b
			public const int sampleTextView = 2131099691;
			
			// aapt resource value: 0x7f060013
			public const int spinner = 2131099667;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DictionaryGameOver = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DictionaryListRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Dictonary = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DictonaryDetail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DictonaryGame = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DictonaryGameStart = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int List = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int spinner_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Tab = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int WordListItem = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040002
			public const int ApplicationName = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int Hello = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int language_prompt = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
