#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Mirapp.Resource", IsApplication=true)]

namespace Mirapp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int Languages = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040008
			public const int GameOverButton = 2130968584;
			
			// aapt resource value: 0x7f040000
			public const int background_app = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int background_list_back = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int background_list_front = 2130968578;
			
			// aapt resource value: 0x7f040006
			public const int background_new_tag = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int line = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int text_description = 2130968580;
			
			// aapt resource value: 0x7f040007
			public const int text_new_tag = 2130968583;
			
			// aapt resource value: 0x7f040003
			public const int text_title = 2130968579;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int book32 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int book48 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int delete2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int delete3 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int edit = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int icon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int list_icon_bg = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int list_item_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int listitem = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int logo = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int trash = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070017
			public const int DictionaryAddButton = 2131165207;
			
			// aapt resource value: 0x7f070018
			public const int DictionaryDeleteButton = 2131165208;
			
			// aapt resource value: 0x7f070026
			public const int DictionaryEasyGameStartButton = 2131165222;
			
			// aapt resource value: 0x7f070024
			public const int DictionaryGameEndButton = 2131165220;
			
			// aapt resource value: 0x7f07001a
			public const int DictionaryGameError = 2131165210;
			
			// aapt resource value: 0x7f07001b
			public const int DictionaryGameFROMButton = 2131165211;
			
			// aapt resource value: 0x7f070007
			public const int DictionaryGameOverResult = 2131165191;
			
			// aapt resource value: 0x7f070000
			public const int DictionaryGameOverResultGameLevel = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int DictionaryGameOverResultLanguage = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int DictionaryGameOverResultSuccessCount = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int DictionaryGameOverResultSuccessPercentage = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int DictionaryGameOverResultSuccessTime = 2131165189;
			
			// aapt resource value: 0x7f070002
			public const int DictionaryGameOverResultTryCount = 2131165186;
			
			// aapt resource value: 0x7f070023
			public const int DictionaryGameResult = 2131165219;
			
			// aapt resource value: 0x7f070025
			public const int DictionaryGameSpinner = 2131165221;
			
			// aapt resource value: 0x7f070006
			public const int DictionaryGameStartAgainButton = 2131165190;
			
			// aapt resource value: 0x7f070022
			public const int DictionaryGameTime = 2131165218;
			
			// aapt resource value: 0x7f07001c
			public const int DictionaryGameToButton1 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int DictionaryGameToButton2 = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int DictionaryGameToButton3 = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int DictionaryGameToButton4 = 2131165215;
			
			// aapt resource value: 0x7f070020
			public const int DictionaryGameToButton5 = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int DictionaryGameToButton6 = 2131165217;
			
			// aapt resource value: 0x7f070028
			public const int DictionaryHardGameStartButton = 2131165224;
			
			// aapt resource value: 0x7f07000f
			public const int DictionaryListRowDelete = 2131165199;
			
			// aapt resource value: 0x7f070011
			public const int DictionaryListRowEdit = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int DictionaryMainButton = 2131165192;
			
			// aapt resource value: 0x7f070027
			public const int DictionaryMediumGameStartButton = 2131165223;
			
			// aapt resource value: 0x7f07000d
			public const int DictonaryRowToWord = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int DictonaryRowWord = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int DictonaryRowWordID = 2131165195;
			
			// aapt resource value: 0x7f070012
			public const int FROMText = 2131165202;
			
			// aapt resource value: 0x7f07000a
			public const int LinearLayoutDictionaryListRow = 2131165194;
			
			// aapt resource value: 0x7f07000e
			public const int LinearLayoutDictionaryListRowButtonDelete = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int LinearLayoutDictionaryListRowButtonEdit = 2131165200;
			
			// aapt resource value: 0x7f07002b
			public const int LinearListCount = 2131165227;
			
			// aapt resource value: 0x7f070029
			public const int LinearListLangugaeSpinner = 2131165225;
			
			// aapt resource value: 0x7f07002c
			public const int ListCount = 2131165228;
			
			// aapt resource value: 0x7f07002a
			public const int ListLangugaeSpinner = 2131165226;
			
			// aapt resource value: 0x7f07002d
			public const int Listview1 = 2131165229;
			
			// aapt resource value: 0x7f070015
			public const int TOText = 2131165205;
			
			// aapt resource value: 0x7f070019
			public const int TranslateButton = 2131165209;
			
			// aapt resource value: 0x7f070016
			public const int TranslatedWordText = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int WordTextAutoComplete = 2131165204;
			
			// aapt resource value: 0x7f07002e
			public const int fragmentContainer = 2131165230;
			
			// aapt resource value: 0x7f070009
			public const int list_icon = 2131165193;
			
			// aapt resource value: 0x7f07002f
			public const int sampleTextView = 2131165231;
			
			// aapt resource value: 0x7f070013
			public const int spinner = 2131165203;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int DictionaryGameOver = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int DictionaryListRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Dictonary = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DictonaryDetail = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int DictonaryGame = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int DictonaryGameStart = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int List = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int Main = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int spinner_item = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Tab = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int WordListItem = 2130903050;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int ApplicationName = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int Hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int language_prompt = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
